### PR TITLE
Fix #11: Add conversion of case insensitive input to real path

### LINKED ISSUE #11: Add conversion of case insensitive input to real path
On windows we can accept case insensitive file names but cppcheck can't work with those> so we have issue like this:
```
C:\Users\danielm\cppcheck>c:\Users\danielm\run-cppcheck\run-cppcheck.exe "c:\Users\danielm\cppcheck\cli\main.cpp"
cppcheck: error: could not find any files matching the filter.
``` 
Because the real name of the disk is `C` and not `c`
Solution: add conversion of the file path to real path.

### PR DESCRIPTION
**Pull request by olabetskyi**

### CODE REVIEW

File: config.cpp [hunk 1]
```diff
@@ -135,6 +135,44 @@ static std::filesystem::path normalizePath(const std::filesystem::path path)
     return result;
 }
 
+std::string Config::matchFilenameFromCompileCommand()
+{
+    // Read compile_commands file
+    std::ifstream ifs(m_projectFilePath);
```
Comment (danmar) [inline config.cpp:141]: please check that the file extension is ".json". if the project file extension is for instance ".cppcheck" then I think we should just leave m_filename as-is, it's not an error.

File: config.cpp [hunk 2]
```diff
@@ -185,11 +226,16 @@ std::string Config::parseArgs(int argc, char **argv)
     if (m_filename.is_relative())
         m_filename = normalizePath(std::filesystem::current_path() / m_filename);
 
+    err = matchFilenameFromCompileCommand();
+    if (!err.empty())
+        return
+            "Failed to find matching file in compile_commands.json: " + err;
```
Comment (danmar) [inline config.cpp:232]: I am not sure that we need to write an error here. We can pass the m_filename as-is and hope that cppcheck manage to deal with it.

Comment (olabetskyi) [reply config.cpp:232]: Fair enough

**Review by danmar — APPROVED** [review]
